[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "example_package_viljarjf"
version = "0.0.1"
authors = [
  { name="Viljar Femoen", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/viljarjf/QM_sim"
"Bug Tracker" = "https://github.com/viljarjf/QM_sim/issues"